#THE FOLLOWING CODE WAS ADAPTED FROM THE FOLLOWING MANUSCRIPT: 
#Marchini, G. L., Arredondo, T. M., & Cruzan, M. B. (2018). 
#Selective differentiation during the colonization and establishment 
#of a newly invasive species. Journal of Evolutionary Biology, 31(11), 1689-1703.

cg <- read.csv("Achmol_common_garden.csv", header = TRUE)
w <- read.csv("Achmol_wild.csv", header = TRUE)

######## DEFINE TRAIT VARIABLES ########
#common garden: 
cgPop <- cg$Population
cgSWL <- cg$SWL
cgLWL <- cg$LWL
cgAL <- cg$AL
#account for angle of achene (subtract 90) 
#and convert paa to radians (deg*(pi/180))
cgPAA <- (cg$PAA-90)*(pi/180)
cgPD <- cg$PD
cgLWW <- cg$LWW
cgSWW <- cg$SWW
cgMASS <- cg$MASS
cgSPSA <- cg$SPSA
cgPL <- cg$PL

#wild: 
wPop <- w$Population
wSWL <- w$SWL
wLWL <- w$LWL
wAL <- w$AL
#account for angle of achene (subtract 90) 
#and convert paa to radians (deg*(pi/180))
wPAA <- (w$PAA-90)*(pi/180)
wPD <- w$PD
wLWW <- w$LWW
wSWW <- w$SWW
wMASS <- w$MASS
wSPSA <- w$SPSA
wPL <- w$PL

######## AMONG POPULATION VARIANCE ########
#get variance among populations from sum of squares generated by ANOVA 
aov(cgSWL ~ cgPop)
aov(cgLWL ~ cgPop)
aov(cgAL ~ cgPop)
aov(cgPAA ~ cgPop)
aov(cgPD ~ cgPop)
aov(cgLWW ~ cgPop)
aov(cgSWW ~ cgPop)
aov(cgMASS ~ cgPop)
aov(cgSPSA ~ cgPop)
aov(cgPL ~ cgPop)

aov(wSWL ~ wPop)
aov(wLWL ~ wPop)
aov(wAL ~ wPop)
aov(wPAA ~ wPop)
aov(wPD ~ wPop)
aov(wLWW ~ wPop)
aov(wSWW ~ wPop)
aov(wMASS ~ wPop)
aov(wSPSA ~ wPop)
aov(wPL ~ wPop)

######## WITHIN POPULATION VARIANCE ######## 
#within population average, variance, and total # of samples function: 
withinVar = function(x) c(mean = mean(x), var = var(x), n = length(x))

#apply function to individual traits
tapply(cgSWL, cgPop, withinVar)
tapply(cgLWL, cgPop, withinVar)
tapply(cgAL, cgPop, withinVar)
tapply(cgPAA, cgPop, withinVar)
tapply(cgPD, cgPop, withinVar)
tapply(cgSWW, cgPop, withinVar)
tapply(cgLWW, cgPop, withinVar)
tapply(cgMASS, cgPop, withinVar)
tapply(cgSPSA, cgPop, withinVar)
tapply(cgPL, cgPop, withinVar)

tapply(wSWL, wPop, withinVar)
tapply(wLWL, wPop, withinVar)
tapply(wAL, wPop, withinVar)
tapply(wPAA, wPop, withinVar)
tapply(wPD, wPop, withinVar)
tapply(wSWW, wPop, withinVar)
tapply(wLWW, wPop, withinVar)
tapply(wMASS, wPop, withinVar)
tapply(wSPSA, wPop, withinVar)
tapply(wPL, wPop, withinVar)

#run ANOVAs for each trait, clustered by population
cg_wvar <- aov(cgSWL ~ cgPop)
cg_wvar <- aov(cgLWL ~ cgPop)
cg_wvar <- aov(cgAL ~ cgPop)
cg_wvar <- aov(cgPAA ~ cgPop)
cg_wvar <- aov(cgPD ~ cgPop)
cg_wvar <- aov(cgLWW ~ cgPop)
cg_wvar <- aov(cgSWW ~ cgPop)
cg_wvar <- aov(cgMASS ~ cgPop)
cg_wvar <- aov(cgSPSA ~ cgPop)
cg_wvar <- aov(cgPL ~ cgPop)

#repeat the following for each trait
summary(cg_wvar)
#Vw is equivalent to the mean sum of squares from ANOVA, which is 
#accessible using the following command: 
vw<-summary(cg_wvar)[1][[1]][[3]][[1]]
vw

######## AMONG POPULATION VARIANCE ######## 
#Va mean for each pop 
#calculate the variance among means
#vector of pop names to average pops together 
meanpops <- c("ALS", "AR", "BLM", "CL", "CM", "CW", "DCR", "DEN", 
              "DR", "MA", "UR2", "UR3", "UTR2", "UW2", "WHS")

#repeat the following for each trait 
bypop <- (tapply(cgPL,cgPop, mean, na.rm=T))
#run one-way ANOVA comparing population means
avar <- aov(bypop~meanpops)
summary(avar)
va<-summary(avar)[1][[1]][[3]][[1]]
va


######## Qst-Fst CONFIDENCE INTERVALS ######## 
#run confidence_intervals_FST.R r
#Fst values can then be imported with the load command 
load("Qst/ci_fst/simFst1000.rda")
#run ff for each trait individually and record the 2.5% and 97.5% CI

#simulation for null distribution
#define function: 
ff<- function(cg2, i){
  #randomly sample population IDs
  ranQ <- sample(cgPop, size = nrow(cg2), replace=FALSE)
  #bind random samples to trait data frame 
  addran <- cbind(ranQ, cg2)
  #run ANOVA to find Vw; CHANGE FOR EVERY TRAIT
  #traits: SWL, LWL, AL, PAA, PD, LWW, SWW
  ranwvar<-aov(cgPL~cgPop)
  #pull Vw from ANOVA
  ranvw<-summary(ranwvar)[1][[1]][[3]][[1]]
  #find mean of trait by population; CHANGE FOR EVERY TRAIT 
  #traits: SWL, LWL, AL, PAA, PD, LWW, SWW
  ranbypop <- (tapply(cgPL,cgPop, mean, na.rm=T))
  ranmeanpops<-c("ALS", "AR", "BLM", "CL", "CM", "CW", "DCR", "DEN", 
                 "DR", "MA", "UR2", "UR3", "UTR2", "UW2", "WHS") 
  #run ANOVA to find Va
  ranavar <- aov(ranbypop~ranmeanpops)
  ranva<-summary(ranavar)[1][[1]][[3]][[1]]
  #assign Fis; global value so consistent for every iteration 
  FIS= -0.0247
  #calculate Qst for run 
  ranQst= (ranva*(1+FIS))/((ranva*(1+FIS))+((4-(2*FIS))*ranvw))
  #pull a random Fst value for run from f function
  ranfst<-sample(simFst1000[i], size=1)
  #report random Qst-Fst calculation
  ranQst-ranfst
}

#library(boot)
#run and report bootstrapping results
bootq <- boot(cg2, ff, R=1000)
summary(bootq$t)
#plot(bootq)

#report 2.5% and 97.5% quantiles 
quantile(bootq$t, c(.025))
quantile(bootq$t, c(.975))
